version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword
    depends_on:
      - db
    networks:
      - fullstack_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fullstack_network

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432" # PostgreSQL'in dışarıya açılan portu 5433 olacak
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack_network

networks:
  fullstack_network:
    driver: bridge

volumes:
  postgres_data:
